require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*
    - spec/*.rb

Lint/ShadowedException:
  Exclude:
    - lib/jekyll-gist/gist_tag.rb

Metrics/AbcSize:
  Exclude:
    - lib/jekyll-gist/gist_tag.rb
